// Deciding whether a turn needs retrieval at all.
//
// "How long do I bake it?" is not an ingredient search, but today it is embedded as
// one, which costs a Gemini request and retrieves recipes the user was never shown.
// Reusing the previous turn's recipes fixes the grounding and saves the request.
//
// SECURITY: the previous turn's sources arrive in the request body, which the client
// controls. Nothing here is trusted as recipe content. Only the slug — validated
// against a strict pattern — and a clamped similarity number leave this module, and
// the caller re-fetches every row from Postgres. A crafted body can at worst name a
// different real recipe; it cannot introduce one that does not exist.
import { isExploratory } from "@/lib/chat-config";
import type { ChatMessage } from "@/lib/chat-types";
import type { Pantry } from "@/lib/ingredients";

// Slugs are generated by the ingest script and are lowercase kebab-case. Anything
// else did not come from the corpus.
export const SLUG_PATTERN = /^[a-z0-9-]{1,128}$/;

// The route retrieves 4. The cap exists so a crafted body cannot widen the grounded
// context far beyond what retrieval would ever produce.
export const MAX_REUSED_SLUGS = 8;

// A recipe the previous turn was grounded in. The similarity is carried forward so
// the rendered context block is byte-identical across turns — which is what makes
// Gemini's implicit prefix cache able to fire at all.
export type PriorSource = {
  slug: string;
  similarity: number;
};

export type ReuseReason =
  | "reuse"
  | "no-prior-sources"
  | "new-ingredients"
  | "exploratory";

export type ReuseDecision = {
  reuse: boolean;
  sources: PriorSource[];
  reason: ReuseReason;
};

function clampSimilarity(value: unknown): number {
  if (typeof value !== "number" || !Number.isFinite(value)) return 0;
  return Math.min(1, Math.max(0, value));
}

// The slugs of the most recent assistant turn, or an empty list. Deliberately does
// not search further back: reuse is about the recipes currently on screen, and an
// assistant turn that retrieved nothing means there is nothing to follow up on.
export function priorSourcesFrom(messages: readonly ChatMessage[]): PriorSource[] {
  for (let i = messages.length - 1; i >= 0; i--) {
    const message = messages[i];
    if (message.role !== "assistant") continue;

    const raw: unknown = (message.metadata as { sources?: unknown } | undefined)?.sources;
    if (!Array.isArray(raw)) return [];

    const sources: PriorSource[] = [];
    const seen = new Set<string>();

    for (const entry of raw) {
      if (sources.length >= MAX_REUSED_SLUGS) break;
      const slug = (entry as { slug?: unknown } | null | undefined)?.slug;
      if (typeof slug !== "string" || !SLUG_PATTERN.test(slug) || seen.has(slug)) continue;
      seen.add(slug);
      sources.push({
        slug,
        similarity: clampSimilarity((entry as { similarity?: unknown }).similarity),
      });
    }

    return sources;
  }

  return [];
}

// The pantry only ever accumulates — it is a Map keyed by normalised term, built over
// every user turn — so a new key is exactly "this turn named something new".
export function hasNewPantryTerms(before: Pantry, after: Pantry): boolean {
  for (const term of after.keys()) {
    if (!before.has(term)) return true;
  }
  return false;
}

// Reuse only when all three conditions hold. Each `false` carries its reason, so a
// reuse rate of zero in the metrics can be diagnosed instead of guessed at.
export function decideReuse({
  priorSources,
  query,
  pantryBefore,
  pantryAfter,
}: {
  priorSources: PriorSource[];
  query: string;
  pantryBefore: Pantry;
  pantryAfter: Pantry;
}): ReuseDecision {
  if (priorSources.length === 0) {
    return { reuse: false, sources: [], reason: "no-prior-sources" };
  }
  // A new ingredient changes the question, so it has to change the answer.
  if (hasNewPantryTerms(pantryBefore, pantryAfter)) {
    return { reuse: false, sources: [], reason: "new-ingredients" };
  }
  // "What else", "other options", "instead of": the user is asking for recipes other
  // than the ones on screen, so reusing those would answer the wrong question.
  if (isExploratory(query)) {
    return { reuse: false, sources: [], reason: "exploratory" };
  }
  return { reuse: true, sources: priorSources, reason: "reuse" };
}
